### ISSUE TITLE
【通知】本项目停止更新

### ISSUE THREAD

**Issue by yutingzhao1991** [yutingzhao1991/github-blogs#150]
自从换了工作，之前自动更新的机器也没了。后来都是自己在手动更新，一直想要重新搞搞也由于拖延症没有搞下来。最近因为安全问题 github 的账号加了 two-factor 的验证，更新的脚本也出了问题，所以索性就停了吧。

其实最开始做这个项目主要是源于一种对信息无法获取的焦虑，总觉得自己错过了很多有价值的内容。尤其是有一段时间大家特别热衷在 github 上面写文章（其实不知道现在还是不是），但是讲道理这个项目这种收集的方式挺暴力的。最初的 list 就是暴力匹配 github 上面名字为 blog 的仓库。后来有自己手动加一些，实际上并没有化太多精力去维护，质量并不高。

当然这个项目对应的[博客列表](https://github.com/yutingzhao1991/github-blogs-collector#%E5%8D%9A%E5%AE%A2%E5%88%97%E8%A1%A8)中还是有部分有价值的博客的，大家也可以关注下。不过除了 github 以外，信息来源的地方还有很多种，比如 [medium](https://medium.com/)， twitter，[dev](https://dev.to/)，收集和整理信息本来也不是一项容易的事情。

可以给大家推荐下 @sorrycc 的日报：https://github.com/sorrycc/zaobao/issues 最近也在公司内部听到 @sorrycc 的信息流的分享，受益良多。推荐了 [rsshub](https://docs.rsshub.app/) [instapaper](https://www.instapaper.com/) 使用等相关的内容，大家如果有什么推荐的关于信息收集和管理的内容也都可以留言回复。

**Comment by chunpu** [comment]
可惜了, 200 多 star 的项目

**Comment by datochan** [comment]
可惜了，自从订阅了这个文章，一直邮件看github的~

**Comment by bbb324** [comment]
可惜了，我看这个订阅从小公司跳到bat，太感谢了




| |
谢峻
邮箱：johnigzie@163.com
|

签名由 网易邮箱大师 定制

在2018年08月26日 18:22，陈俊州 写道：

可惜了，自从订阅了这个文章，一直邮件看github的~

**Comment by cssmagic** [comment]
可惜了。每周必看，接收了不少有用的信息，感谢！不过还是尊重楼主的选择，祝好 :+1:

**Comment by 1615450788** [comment]
每周必看-。-  感谢🙏

**Comment by flashback313** [comment]
一直看，谢谢楼主的贡献

**Comment by kujian** [comment]
欢迎去我的项目看看：https://github.com/kujian/frontendDaily

**Comment by qiwihui** [comment]
@yutingzhao1991 
这个项目停止了确实有些可惜。关于博主提到的以下两个问题其实可以很容易解决，而且不需要修改js逻辑。

1. github 的账号加了 two-factor 的验证导致脚本出错问题。
2. 自动更新的机器没了；

### 解决办法：

1. 在 github `Settings -> Developer settings -> Personal access tokens` 页面配置一个 access token 来解决two-factor 验证，这也是 github 本身推荐的。

![image](https://user-images.githubusercontent.com/3297411/47772527-e6c30580-dd21-11e8-89ce-7ae3335c9f86.png)

2. 使用 Travis-ci 的定时任务来解决手动手动执行的问题。travis除了可以在每次 push 的时候触发，还可以设置定时任务。

（1）在项目中配置 travis 的配置，以下是我的项目中的配置（需要修改中文部分）。

```yaml
language: node_js
node_js:
- 6.9.0
install:
- npm install
script:
- node src/harvest-bootstrap.js <你的github ID> $GITHUB_TOKEN weekly
branches:
  only:
  - master
cache:
  directories:
  - node_modules
notifications:
  email:
    recipients:
    - <你的邮箱>
    on_success: change
    on_failure: always
```

（2）在 https://travis-ci.org 中添加项目，并配置一个 GITHUB_TOKEN 的环境变量：

![image](https://user-images.githubusercontent.com/3297411/47772544-f17d9a80-dd21-11e8-972c-3dd4abbe0392.png)

（3）配置定时Cron任务，文档见 [Cron Jobs](https://docs.travis-ci.com/user/cron-jobs/)

![image](https://user-images.githubusercontent.com/3297411/47772553-f80c1200-dd21-11e8-94b0-46b8c650996e.png)

以上就可以解决了。结果可以参见 [Travis任务结果](https://travis-ci.org/qiwihui/github-blogs-collector/builds/448713623)，以及对应的 [github-blogs-weekly](https://github.com/qiwihui/github-blogs-weekly)
